
 void main() {
  
  // This is my home work.
  
  String name = " Sharifa";
  String lastName = "Joya";
  int age = 24;
  double height = 1.69; 
  bool doYouLikeCoding = true;
  
  print("Hi! I'm" +name +".");
  
  print("My last name is $lastName so I'm $age years old.");
  print("I am $height meters tall.");
 
  print("Do I like coding? $doYouLikeCoding."); 
}
    
//This is my home work in sesion 3, doing data type.
  
 int age = 35; // interger 
  
double pi = 3.14; // double( deci,al numbers)
  
String countery = "Afghanistan"; // String 
 
print( " Hello form $countery! \n pi is $pi and the age should be $age.");
    
